<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 End notes | Exploring Nighttime Light in the U.S. Southeast</title>
  <meta name="description" content="5 End notes | Exploring Nighttime Light in the U.S. Southeast" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="5 End notes | Exploring Nighttime Light in the U.S. Southeast" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 End notes | Exploring Nighttime Light in the U.S. Southeast" />
  
  
  

<meta name="author" content="Daniel Moul" />


<meta name="date" content="2021-09-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="interpreting-the-results.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="libs/vis-4.20.1/vis.css" rel="stylesheet" />
<script src="libs/vis-4.20.1/vis.min.js"></script>
<script src="libs/visNetwork-binding-2.0.9/visNetwork.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://dmoul.github.io/nightlight/introduction.html target="_blank">Exploring Nighttime Light</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#questions"><i class="fa fa-check"></i><b>1.1</b> Questions</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#method"><i class="fa fa-check"></i><b>1.2</b> Method</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#causal-assumptions"><i class="fa fa-check"></i><b>1.3</b> Causal assumptions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>2</b> Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#map"><i class="fa fa-check"></i><b>2.1</b> Map</a></li>
<li class="chapter" data-level="2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#data-for-modeling"><i class="fa fa-check"></i><b>2.2</b> Data for modeling</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#predictors-and-data-transformations"><i class="fa fa-check"></i><b>2.2.1</b> Predictors and data transformations</a></li>
<li class="chapter" data-level="2.2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#radiance-values-distribution-by-state"><i class="fa fa-check"></i><b>2.2.2</b> Radiance values’ distribution by state</a></li>
<li class="chapter" data-level="2.2.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#r2-and-linear-relationships-slope-estimates-by-state"><i class="fa fa-check"></i><b>2.2.3</b> <span class="math inline">\(R^2\)</span> and linear relationships: slope estimates by state</a></li>
<li class="chapter" data-level="2.2.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#eda-summary-comments"><i class="fa fa-check"></i><b>2.2.4</b> EDA summary comments</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html"><i class="fa fa-check"></i><b>3</b> Modeling and model comparison</a>
<ul>
<li class="chapter" data-level="3.1" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#train-and-test-on-training-data-set"><i class="fa fa-check"></i><b>3.1</b> Train and test on training data set</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#lin1-pop_density-light_avg"><i class="fa fa-check"></i><b>3.1.1</b> lin1: pop_density ~ light_avg</a></li>
<li class="chapter" data-level="3.1.2" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#lin2-pop_density_official-light_avg"><i class="fa fa-check"></i><b>3.1.2</b> lin2: pop_density_official ~ light_avg</a></li>
<li class="chapter" data-level="3.1.3" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#lin3-log_pop_density-log_light_avg"><i class="fa fa-check"></i><b>3.1.3</b> lin3: log_pop_density ~ log_light_avg</a></li>
<li class="chapter" data-level="3.1.4" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#pol1-log_light_avg-polylog_pop_density-2"><i class="fa fa-check"></i><b>3.1.4</b> pol1: log_light_avg ~ poly(log_pop_density, 2)</a></li>
<li class="chapter" data-level="3.1.5" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#lme1-multi-level-model-with-lme4lmer"><i class="fa fa-check"></i><b>3.1.5</b> lme1: multi-level model with <span>lme4::lmer</span></a></li>
<li class="chapter" data-level="3.1.6" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#bs1-linear-model-with-b-spline"><i class="fa fa-check"></i><b>3.1.6</b> bs1: linear model with b-spline</a></li>
<li class="chapter" data-level="3.1.7" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#xgboost-log_pop_density-log_light_avg-state"><i class="fa fa-check"></i><b>3.1.7</b> XGBoost: log_pop_density ~ log_light_avg + state</a></li>
<li class="chapter" data-level="3.1.8" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#summary-of-train-test-results"><i class="fa fa-check"></i><b>3.1.8</b> Summary of train-test results</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#assessing-model-performance-with-the-holdout-data-set"><i class="fa fa-check"></i><b>3.2</b> Assessing model performance with the holdout data set</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#summary-model-evaluation-using-holdout-data-set"><i class="fa fa-check"></i><b>3.2.1</b> Summary: model evaluation using holdout data set</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#comparing-2000-and-2010"><i class="fa fa-check"></i><b>3.3</b> Comparing 2000 and 2010</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="modeling-and-model-comparison.html"><a href="modeling-and-model-comparison.html#summary-model-performance-on-census-2010-data."><i class="fa fa-check"></i><b>3.3.1</b> Summary: model performance on census 2010 data.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="interpreting-the-results.html"><a href="interpreting-the-results.html"><i class="fa fa-check"></i><b>4</b> Interpreting the results</a>
<ul>
<li class="chapter" data-level="4.1" data-path="interpreting-the-results.html"><a href="interpreting-the-results.html#how-much-did-the-population-density-and-radiance-change-between-2000-and-2010"><i class="fa fa-check"></i><b>4.1</b> How much did the population density and radiance change between 2000 and 2010?</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="interpreting-the-results.html"><a href="interpreting-the-results.html#from-2000-to-2010-radiance-increased-almost-twice-as-much-as-population-density"><i class="fa fa-check"></i><b>4.1.1</b> From 2000 to 2010 radiance increased almost twice as much as population density</a></li>
<li class="chapter" data-level="4.1.2" data-path="interpreting-the-results.html"><a href="interpreting-the-results.html#exploring-changes-in-radiance-and-population-density-2000-and-2010"><i class="fa fa-check"></i><b>4.1.2</b> Exploring changes in radiance and population density 2000 and 2010</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="interpreting-the-results.html"><a href="interpreting-the-results.html#conclusion"><i class="fa fa-check"></i><b>4.2</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="end-notes.html"><a href="end-notes.html"><i class="fa fa-check"></i><b>5</b> End notes</a>
<ul>
<li class="chapter" data-level="5.1" data-path="end-notes.html"><a href="end-notes.html#acknowlegements"><i class="fa fa-check"></i><b>5.1</b> Acknowlegements</a></li>
<li class="chapter" data-level="5.2" data-path="end-notes.html"><a href="end-notes.html#data-provenance"><i class="fa fa-check"></i><b>5.2</b> Data provenance</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="end-notes.html"><a href="end-notes.html#version-4-dmsp-ols-nighttime-lights-time-series"><i class="fa fa-check"></i><b>5.2.1</b> Version 4 DMSP-OLS Nighttime Lights Time Series</a></li>
<li class="chapter" data-level="5.2.2" data-path="end-notes.html"><a href="end-notes.html#radiance-data"><i class="fa fa-check"></i><b>5.2.2</b> Radiance data</a></li>
<li class="chapter" data-level="5.2.3" data-path="end-notes.html"><a href="end-notes.html#intercalibration"><i class="fa fa-check"></i><b>5.2.3</b> Intercalibration</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="end-notes.html"><a href="end-notes.html#assumptions-and-limitations"><i class="fa fa-check"></i><b>5.3</b> Assumptions and limitations</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="end-notes.html"><a href="end-notes.html#limitations"><i class="fa fa-check"></i><b>5.3.1</b> Limitations</a></li>
<li class="chapter" data-level="5.3.2" data-path="end-notes.html"><a href="end-notes.html#census-data-and-state-and-county-geometry"><i class="fa fa-check"></i><b>5.3.2</b> Census data and state and county geometry</a></li>
<li class="chapter" data-level="5.3.3" data-path="end-notes.html"><a href="end-notes.html#population-and-population-density"><i class="fa fa-check"></i><b>5.3.3</b> Population and population density</a></li>
<li class="chapter" data-level="5.3.4" data-path="end-notes.html"><a href="end-notes.html#economic-development-gdp-business-cycle"><i class="fa fa-check"></i><b>5.3.4</b> Economic development / GDP / business cycle</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="end-notes.html"><a href="end-notes.html#project-organization"><i class="fa fa-check"></i><b>5.4</b> Project organization</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="end-notes.html"><a href="end-notes.html#data-preparation-pipeline-implemented-to-with-targets-package"><i class="fa fa-check"></i><b>5.4.1</b> Data preparation pipeline implemented to with targets package</a></li>
<li class="chapter" data-level="5.4.2" data-path="end-notes.html"><a href="end-notes.html#session-information"><i class="fa fa-check"></i><b>5.4.2</b> Session information</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://dmoul.github.io" target="_blank">By Daniel Moul</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Nighttime Light in the U.S. Southeast</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="end-notes" class="section level1" number="5">
<h1><span class="header-section-number">5</span> End notes</h1>
<div id="acknowlegements" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Acknowlegements</h2>
<p>Image and data processing by Earth Observation Group, Payne Institute for Public Policy, Colorado School of Mines. DMSP data collected by US Air Force Weather Agency.</p>
<p>Special thanks to …</p>
<ul>
<li><p>Daynan Crull, Trevor Monroe and the world bank for their <a href="https://worldbank.github.io/OpenNightLights/welcome.html">Open Night Lights tutorial</a>, presented as part of the <a href="https://www.geo4.dev/events/symposium">3rd Annual Geo4Dev Symposium &amp; Workshop</a> December 10-11, 2020.</p></li>
<li><p>Robin Lovelace, Jakub Nowosad, and Jannes Muenchow for the very helpful <a href="https://geocompr.robinlovelace.net">Geocomputation with R</a>, which is now available as a physical book from CRC Press.</p></li>
<li><p>Edzer Pebesma and all those who have been working on sf and terra in recent years. July 2021 overview: <a href="https://edzer.github.io/UseR2021/#1" class="uri">https://edzer.github.io/UseR2021/#1</a></p></li>
<li><p>Kyle Walker, Matt Herman, and Kris Eberwein for the <a href="https://CRAN.R-project.org/package=tidycensus">tidycensus</a> package</p></li>
<li><p>The RStudio team and other contributors to the tidyverse and tidymodels package families.</p></li>
<li><p>Max Kuhn and Julia Silge for <a href="https://www.tmwr.org">Tidy Modeling with R</a>. I used Version 0.0.1.9010 (2021-07-19).</p></li>
<li><p>CRAN maintainers and the R Foundation for fostering a high-quality, growing R ecosystem.</p></li>
</ul>
<p><br></p>
</div>
<div id="data-provenance" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Data provenance</h2>
<div id="version-4-dmsp-ols-nighttime-lights-time-series" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Version 4 DMSP-OLS Nighttime Lights Time Series</h3>
<p>From <a href="https://eogdata.mines.edu/products/dmsp/" class="uri">https://eogdata.mines.edu/products/dmsp/</a></p>
<blockquote>
<p>Since the 1970s, the U.S. Air Force Defense Meteorological Satellite Program (DMSP) has operated satellite sensors capable of detecting the visible and near-infrared (VNIR) emissions from cities and towns. The DMSP Operational Linescan System (OLS) acquires global daytime and nighttime imagery of the
Earth in two spectral bands (VIS and TIR). The nighttime “VIS” bandpass straddles the VNIR portion of the spectrum (0.5 to 0.9 um). The VIS band signal is intensified at night using a photomultiplier tube (PMT), making it possible to detect faint VNIR emission sources. The PMT system was implemented for the detection of clouds at night. An unanticipated consequence of the nighttime light intensification is the detection of city lights, gas flares, and fires.</p>
<p>Since 1997, EOG had been pioneering in combining the imagery taken by DMSP-OLS to produce global Nighttime Light maps. With annual data stretch from 1992 to 2013, making DMSP Nighttime Light the longest data series available for nocturnal remote sensing on human activities.</p>
</blockquote>
<p><br></p>
<p>From <a href="https://eogdata.mines.edu/dmsp/downloadV4composites.html" class="uri">https://eogdata.mines.edu/dmsp/downloadV4composites.html</a></p>
<blockquote>
<p>The files are cloud-free composites made using all the available archived DMSP-OLS smooth resolution data for calendar years. In cases where two satellites were collecting data - two composites were produced. The products are 30 arc second grids, spanning -180 to 180 degrees longitude and -65 to 75 degrees latitude.</p>
<p>Citations:</p>
<p>These data sets are the results of years of algorithm development and production efforts. The data are here for you and others to use in any way you like and have no copyright. Please acknowledge our efforts by including a brief data source attribution and one or more of the following references in anything you write where our data is utilized. Data source attribution “Earth Observation Group, Colorado School of Mines.”</p>
<p>References:</p>
<p>Elvidge, C. D., Baugh, K. E., Kihn, E. A., Kroehl, H. W., &amp; Davis, E. R. (1997). Mapping city lights with nighttime data from the DMSP Operational Linescan System. Photogrammetric Engineering and Remote Sensing, 63(6), 727-734.</p>
<p>Baugh, K., Elvidge, C. D., Ghosh, T., &amp; Ziskin, D. (2010). Development of a 2009 stable lights product using DMSP-OLS data. Proceedings of the Asia-Pacific Advanced Network, 30(0), 114.</p>
</blockquote>
<p><br></p>
</div>
<div id="radiance-data" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Radiance data</h3>
<p>I use Radiance Calibrated values<span class="citation">(<a href="#ref-rs70201855" role="doc-biblioref">Hsu et al. 2015</a>)</span>, a transformation of the Digital Number (DN) made available by the EOG group at <a href="https://eogdata.mines.edu/products/dmsp/#v4_dmsp_download" class="uri">https://eogdata.mines.edu/products/dmsp/#v4_dmsp_download</a></p>
<p>From <a href="https://eogdata.mines.edu/products/dmsp/#radcal" class="uri">https://eogdata.mines.edu/products/dmsp/#radcal</a> :</p>
<blockquote>
<p>The Operational Linescan System (OLS) flown on the Defense Meteorological Satellite Program (DMSP) satellites, has a unique capability to record low light imaging data at night worldwide. These data are archived at the National Oceanic and Atmospheric Administration (NOAA) National Geophysical Data Center (NGDC). The useful data record stretches back to 1992 and is ongoing. The OLS visible band detector observes radiances about one million times dimmer than most other Earth observing satellites. The sensor is typically operated in a high gain setting to enable the detection of moonlit clouds. However, with six bit quantization and limited dynamic range, the recorded data are saturated in the bright cores of urban centers. A limited set of observations have been obtained at low lunar illumination were obtained where the gain of the detector was set significantly lower than its typical operational setting (sometimes by a factor of 100). By combining these sparse data acquired at low gain settings with the operational data acquired at high gain settings, we have produced a set of global nighttime lights product with no sensor saturation. This product can be related to radiances based on the pre-flights sensor calibration.</p>
</blockquote>
<p>See the <a href="https://eogdata.mines.edu/dmsp/radcal_readme.txt">Global Radiance Calibrated Nighttime Lights Product Readme</a> for a summary of the methodology.</p>
<p>These files align with the US decennial census, which has the highest-quality demographic data. I downloaded the image files on 2021-07-17.</p>
<ul>
<li><p>F12-F15_20000103-20001229_rad_v4.geotiff.tgz (F12-F15_20000103-20001229_rad_v4); using F12-F15_20000103-20001229_rad_v4.avg_vis.tif</p></li>
<li><p>F16_20100111-20110731_rad_v4.geotiff.tgz (F16_20100111-20110731_rad_v4); using F16_20100111-20110731_rad_v4.avg_vis.tif</p></li>
</ul>
<p><br></p>
</div>
<div id="intercalibration" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Intercalibration</h3>
<p><a href="https://eogdata.mines.edu/products/dmsp/" class="uri">https://eogdata.mines.edu/products/dmsp/</a></p>
<p>I use the EOG’s Radiance Calibrated products, which have data for the years I want and requires intersatellite and inter-annual calibration in order to make valid comparisons. The coefficient table is available in <em>DMSP-OLS Radiance Calibrated Nighttime Lights Time Series with Intercalibration</em><span class="citation">(<a href="#ref-rs70201855" role="doc-biblioref">Hsu et al. 2015</a>)</span>:</p>
<blockquote>
<p>The Defense Meteorological Satellite Program-Operational Linescan
System (DMSP-OLS) stable lights products are made using operational
OLS data collected at high gain settings, resulting in sensor
saturation on brightly lit areas, such as city centers. This has been
a paramount shortcoming of the DMSP-OLS stable lights time series.
This study outlines a methodology that greatly expands the dynamic
range of the OLS data using observations made at different fixed-gain
settings, and by incorporating the areas not affected by saturation
from the stable lights product. The radiances for the fixed-gain data
are computed based on each OLS sensor’s pre-flight calibration. The
result is a product known as the OLS radiance calibrated nighttime
lights. A total of eight global datasets have been produced,
representing years from 1996 to 2010. To further facilitate the
usefulness of these data for time-series analyses, corrections have
been made to counter the sensitivity differences of the sensors, and
coefficients are provided to adjust the datasets to allow
inter-comparison.</p>
</blockquote>
<p>page 1868 includes the relevant coefficients, as does the <a href="https://eogdata.mines.edu/dmsp/radcal_readme.txt">Global Radiance Calibrated Nighttime Lights Product Readme</a>:</p>
<p>Inter-satellite Calibration Multiplier.</p>
<table>
<thead>
<tr class="header">
<th>Satellite</th>
<th>Base Gain (dB)</th>
<th>Multiplier</th>
<th>Radiance @ DN1 (W/cm2/sr)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F14</td>
<td>55</td>
<td>0.82</td>
<td>1.23E-10</td>
</tr>
<tr class="even">
<td>F16</td>
<td>55</td>
<td>1.0</td>
<td>1.50E-10</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Note all [radiance] products are inter-satellite calibrated to the
base gain setting of 55 dB of satellite F16. (page 1872)</p>
</blockquote>
<p>Thus, to perform inter-satellite calibration, I multiplied the radiance values in the F14 GeoTIFF image by 0.82. While this improves the comparability in time series, it contributes its own sources of error, as summarized below.</p>
<p>I take the Inter-annual Calibration Coefficients directly from the <a href="https://eogdata.mines.edu/dmsp/radcal_readme.txt">Global Radiance Calibrated Nighttime Lights Product Readme</a>:</p>
<pre><code>  NOTE: (1) This table is preliminary, and needs to be updated.
        (2) There is no data for &quot;F16_20051128-20061224_rad_v4&quot; for it being
            the reference dataset.
        (3) F16_20100111-20101209_rad_v4 and F16_20100111-20110731_rad_v4 share
            the same data for there is onyl small diferrence from adding images
            from year 2011.

  Equation
  Y=Coeff0+Coeff1*X
  
  Y-File
  F16_20051128-20061224_rad_v4
  
  X-File                           Pow Coeff0  Coeff1 R2    N_Pt
  F12_19960316-19970212_rad_v4     1   4.336   0.915  0.971 20540
  F12_19990119-19991211_rad_v4     1   1.423   0.780  0.980 20846 
  F12-F15_20000103-20001229_rad_v4 1   3.658   0.710  0.980 20866 &lt;-
  F14-F15_20021230-20031127_rad_v4 1   3.736   0.797  0.980 20733
  F14_20040118-20041216_rad_v4     1   1.062   0.761  0.984 20844
  F16_20100111-20101209_rad_v4     1   2.196   1.195  0.981 20848 &lt;-
  F16_20100111-20110731_rad_v4     1  -1.987   1.246  0.981 20848
  </code></pre>
<p>Thus to make values comparable across years, I further transform the 2000 radiance values: <span class="math display">\[Y=Coeff_0+Coeff_1 * X = 3.658 + 0.710 * X\]</span></p>
<p>where X is the vector of radiance values. Similarly for 2010: <span class="math display">\[Y=Coeff_0+Coeff_1 * X = 2.196 + 1.195 * X\]</span></p>
<p>Note the <span class="math inline">\(R^2\)</span> values above. This adjustment is introducing error.</p>
<p><br></p>
</div>
</div>
<div id="assumptions-and-limitations" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Assumptions and limitations</h2>
<div id="limitations" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Limitations</h3>
<div id="limitations-in-nighttime-lights-data" class="section level4" number="5.3.1.1">
<h4><span class="header-section-number">5.3.1.1</span> Limitations in nighttime lights data</h4>
<p>The World Bank’s <em>Open Nighttime Lights</em> tutorial <span class="citation">(<a href="#ref-WBONT2020" role="doc-biblioref">WorldBank 2020</a>)</span> summarizes the following limitations (among others):</p>
<blockquote>
<p>2.2.2. Limitations and challenges of DMSP-OLS</p>
<ul>
<li>Low radiometric resolution (6-bit data, values range from 0-63)</li>
<li>No on-board calibration</li>
<li>Large spatial resolution (4.9km for nighttime VIS band)</li>
<li>Saturation in urban cores</li>
</ul>
</blockquote>
<blockquote>
<p>These limitations can lead to challenges for scientists using these data for their work. For example, drawing conclusions from the DMSP-OLS
stable lights series may be challenging in low-density urban areas …. In addition, the extent and intensity of lit areas cannot directly
delimit urban regions due to the “blooming” effect.</p>
</blockquote>
<p>Therefore I use the Radiance Calibrated products. Note however that they are not absolute radiance<span class="citation">(<a href="#ref-rs70201855" role="doc-biblioref">Hsu et al. 2015</a>)</span></p>
<blockquote>
<p>Many users would like to relate the DN values in the Radiance Calibrated products to actual radiance. The fixed-gain image avoids the automatic gain variation by VDGA which is not recorded in the data stream. So theoretically, by applying the preflight sensor calibration, the actual radiance could be derived from the DN. Nevertheless, even under such controlled operation, there is no means to address the degradation of the equipment without an on board calibration device. Moreover, the uncertainty brought by blending Stable Light products, which were taken under variable gain settings, make it even more unlikely to derive the exact radiance from the Radiance Calibrated product. As a result, it is suggested that the Radiance Calibrated product is only suitable for analyses which do not require actual radiance. Nevertheless, the conversion factor from DN to radiance for the Radiance Calibrated products is listed in Table 3 for reference. Note all products are inter-satellite calibrated to the base gain setting of 55 dB of satellite F16. (page 1872)</p>
</blockquote>
<p>and</p>
<blockquote>
<p>Because the DMSP-OLS does not carry an on-board calibration device for the visible band, it is not possible to track how actual radiance is being converted to DN even if the auto-adjust gain setting is fixed. Instead we rely on the preflight calibration made for each OLS instrument prior to launch. Therefore, even though the Radiance Calibrated products are made from data collected under much more controlled setting than the Stable Lights products, the radiance values should still be considered relative and not absolute. (page 1874)</p>
</blockquote>
<p>In this analysis I refer to these Radiance Calibrated values as “radiance” and “radiance values”</p>
</div>
<div id="limitations-in-intercalibration" class="section level4" number="5.3.1.2">
<h4><span class="header-section-number">5.3.1.2</span> Limitations in intercalibration</h4>
<p>As summarized in <span class="citation">(<a href="#ref-rs70201855" role="doc-biblioref">Hsu et al. 2015</a>)</span></p>
<blockquote>
<p>Being freed from the saturation problem, Radiance Calibrated products need a reference area which not only is stable enough but also provides samples with brightness ranging from very low light to the world’s highest levels. Los Angeles was taken as the reference for the Radiance Calibrated products for two reasons. First, Los Angeles has long been a mature metropolis and the light change is negligible. Second, being a metropolis, it can provide samples with high DNs from the city center, as well as low DNs from the suburban area.</p>
</blockquote>
<p>While the distribution of light data from L.A. over the time period may have been relatively stable, the differences probably weren’t zero, and the error or bias is not quantified. In fact the <a href="https://eogdata.mines.edu/dmsp/radcal_readme.txt">readme</a> includes the following related to inter-annual calibration:</p>
<blockquote>
<ol style="list-style-type: decimal">
<li>This table is preliminary, and needs to be updated.</li>
</ol>
</blockquote>
<p>The readme includes the following:</p>
<pre><code>Date: 01/15/2015
Modified: 09/09/2020</code></pre>
<p>Typical uncertainty of sensors noted in <span class="citation">(<a href="#ref-CHFWXB2013" role="doc-biblioref">Chander et al. 2013</a>)</span>:</p>
<blockquote>
<p>In general, the absolute radiometric calibration for most optical
sensors is specified to an uncertainty of 5%; hence, the likely
uncertainty (in reflectance units) on a measured reflectance value of,
for example, 0.4 will be ±5% of 0.4 equal to ±0.02. (page 1058)</p>
</blockquote>
<p>Scene Variability can source of error, however in this case, use of light averaged over data collected at various times throughout the year minimizes this source of error.</p>
<blockquote>
<p>The intercalibration of satellite instruments often requires
comparing observations from different instruments coincident
in space, time, and viewing geometry. As these are never
exactly aligned, thresholds are usually applied to define the
collocations. The choice of these thresholds directly impacts
the uncertainty of the comparison, partially due to the scene
variability within the range of the collocation criteria. The
collocation criteria represent tradeoffs between the errors on
each collocation and the number of collocations available.
Collocated observations from a pair of satellite instruments are
not sampled at exactly the same place or time. Variations in
the atmosphere and surface during the interval between their
observations introduce errors when comparing their collocated
radiances. The greater the collocated observations interval, the
larger the contribution of the scene’s variability to the total error
budget. (page 1061)</p>
</blockquote>
<p><br></p>
</div>
</div>
<div id="census-data-and-state-and-county-geometry" class="section level3" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Census data and state and county geometry</h3>
<p>This analysis used three sources of data:</p>
<ol style="list-style-type: decimal">
<li>US census 2000, which provided total population by county and median income by county.</li>
<li>US census 2010, which provided total population by county. This decennial census did not provide median household income (in fact, the 2010 census did away with the “long form” that provided the data for the sf3 table).</li>
<li>I initially used the five-year ACS (2006-2010), which provided total population by county and median income by county, however once I decided not to use median income, I didn’t need the ACS. Which is good since ACS population estimates are ~2% lower than the 2010 census for the counties I examined in this analysis, and I did not need to deal with differences in methodology between the decennial census and ACS, or adjust for inflation.</li>
</ol>
<p>The <a href="https://CRAN.R-project.org/package=tidycensus">tidycensus</a> package provides the population data from 2000 and 2010 decennial censuses. Median income per family comes from the decennial 2000 census and the American Community Survey (ACS) five-year estimates 2006-2010 provided by the US Census Bureau. <code>tidycensus</code> also provides state and county geometry via the <a href="https://journal.r-project.org/archive/2016/RJ-2016-043/RJ-2016-043.pdf">tigris</a> package (and corresponding extracts from the Census Bureau’s Master Address File/Topologically Integrated Geographic Encoding and Referencing (TIGER) database).</p>
</div>
<div id="population-and-population-density" class="section level3" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Population and population density</h3>
<p>I used these county boundaries to calculate the area of each county and (combined with decennial census population), each county’s population density. I included land and water area when calculating total area, since my calculation of average light radiance per county used the same boundaries that included land and water within those boundaries</p>
<p>I did not do anything to adjust for light blooming beyond whatever the EOG did in their Radiance Calibrated products. Instead I assume blooming artifacts are similar in the 2000 and 2010 products.</p>
<p>On the coasts and in other high-traffic areas, census population (and therefore population density) may not capture vacationers and other itinerant people that contribute to population density, the capacity of the build environment, and (if my causal conjecture holds), the degree to which an area is built up and generated light. I assume any effect due to itinerant people is small enough (or consistent across the time interval) that it can be ignored.</p>
</div>
<div id="economic-development-gdp-business-cycle" class="section level3" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Economic development / GDP / business cycle</h3>
<p>The US was in the middle of the Great Recession in 2010. Could this be a factor in the lower radiance levels that year compared to 2000? Starting in 2008, the recession depressed new investments, including building projects that would have created more nighttime light. This may have contributed to slower growth in radiance, however it’s unlikely to have caused light levels in 2010 to be <strong><em>lower</em></strong> than 2000. Consider: shopping malls and hotels may have had lower occupancy and fewer customers, but they would have left the lights on in their parking lots.</p>
<p><br></p>
</div>
</div>
<div id="project-organization" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Project organization</h2>
<div id="data-preparation-pipeline-implemented-to-with-targets-package" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Data preparation pipeline implemented to with targets package</h3>
<p>I used the <code>targets</code> package to define a pipeline for data preparation. Dependencies among the set of functions are specified in the <em>_targets</em> file and executed via <code>tar_make()</code>. They include the following:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="end-notes.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tar_manifest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb68-2"><a href="end-notes.html#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb68-3"><a href="end-notes.html#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code></pre></div>
<pre><code>## here() starts at /Users/dmoul/rwork/nightlight</code></pre>
<div id="yyichzgjis" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#yyichzgjis .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#yyichzgjis .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yyichzgjis .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yyichzgjis .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yyichzgjis .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yyichzgjis .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yyichzgjis .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#yyichzgjis .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#yyichzgjis .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#yyichzgjis .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#yyichzgjis .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#yyichzgjis .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#yyichzgjis .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#yyichzgjis .gt_from_md > :first-child {
  margin-top: 0;
}

#yyichzgjis .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yyichzgjis .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#yyichzgjis .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#yyichzgjis .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yyichzgjis .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#yyichzgjis .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yyichzgjis .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#yyichzgjis .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#yyichzgjis .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yyichzgjis .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yyichzgjis .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#yyichzgjis .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yyichzgjis .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#yyichzgjis .gt_left {
  text-align: left;
}

#yyichzgjis .gt_center {
  text-align: center;
}

#yyichzgjis .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yyichzgjis .gt_font_normal {
  font-weight: normal;
}

#yyichzgjis .gt_font_bold {
  font-weight: bold;
}

#yyichzgjis .gt_font_italic {
  font-style: italic;
}

#yyichzgjis .gt_super {
  font-size: 65%;
}

#yyichzgjis .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">command</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">pattern</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">all_df</td>
<td class="gt_row gt_left">model_prepare_data(county_sf)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">all_df_c</td>
<td class="gt_row gt_left">model_prepare_data(county_sf_c)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">bbox_vec</td>
<td class="gt_row gt_left">get_bbox(census_df, these_states)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">census_df</td>
<td class="gt_row gt_left">get_census_data(all_states, census_year_a, "census")</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">census_df_c</td>
<td class="gt_row gt_left">get_census_data(all_states, census_year_c, "census")</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">census_focus_df</td>
<td class="gt_row gt_left">census_focus(census_df, these_states, bbox_vec)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">census_focus_df_c</td>
<td class="gt_row gt_left">census_focus(census_df_c, these_states, bbox_vec)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">county_sf</td>
<td class="gt_row gt_left">get_county_light_sf(census_focus_df, light_sf)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">county_sf_c</td>
<td class="gt_row gt_left">get_county_light_sf(census_focus_df_c, light_sf_c)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">light_points_df</td>
<td class="gt_row gt_left">get_light_levels(bbox_vec, source_light_file_2000,  \n     intersat_calibration = 0.82, interannual_calibration = c(3.658,  \n         0.71))</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">light_points_df_c</td>
<td class="gt_row gt_left">get_light_levels(bbox_vec, source_light_file_2010,  \n     intersat_calibration = 1, interannual_calibration = c(2.196,  \n         1.195))</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">light_sf</td>
<td class="gt_row gt_left">get_light_sf(light_points_df, state_boundaries_geom)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">light_sf_c</td>
<td class="gt_row gt_left">get_light_sf(light_points_df_c, state_boundaries_geom)</td>
<td class="gt_row gt_left">NA</td></tr>
    <tr><td class="gt_row gt_left">state_boundaries_geom</td>
<td class="gt_row gt_left">state_boundaries(census_focus_df)</td>
<td class="gt_row gt_left">NA</td></tr>
  </tbody>
  
  
</table>
</div>
<p><br></p>
<p><code>tar_visnetwork()</code> draws a dependency graph. Zoom in to see the labels on the nodes:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="end-notes.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tar_visnetwork</span>()</span></code></pre></div>
<pre><code>## here() starts at /Users/dmoul/rwork/nightlight</code></pre>
<div id="htmlwidget-9abb3486349adfa5d821" style="width:672px;height:480px;" class="visNetwork html-widget"></div>
<script type="application/json" data-for="htmlwidget-9abb3486349adfa5d821">{"x":{"nodes":{"name":["all_df","all_df_c","bbox_vec","census_df","census_df_c","census_focus_df","census_focus_df_c","county_sf","county_sf_c","light_points_df","light_points_df_c","light_sf","light_sf_c","state_boundaries_geom","get_light_sf","get_bbox","get_census_data","get_county_light_sf","source_light_file_2000","get_light_levels","source_light_file_2010","these_states","model_prepare_data","all_states","state_boundaries","census_year_a","census_year_b","census_focus","census_year_c"],"type":["stem","stem","stem","stem","stem","stem","stem","stem","stem","stem","stem","stem","stem","stem","function","function","function","function","object","function","object","object","function","object","function","object","object","function","object"],"status":["uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate","uptodate"],"seconds":[0.999,0.143,0.012,21.935,7.448,3.158,1.273,28.522,29.061,6.306,1.472,50.865,52.457,17.62,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"bytes":[137144,115221,450,2892945,3072067,2665516,2846813,22074131,21009321,11428419,9909579,20562775,19636232,385405,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"branches":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"id":["all_df","all_df_c","bbox_vec","census_df","census_df_c","census_focus_df","census_focus_df_c","county_sf","county_sf_c","light_points_df","light_points_df_c","light_sf","light_sf_c","state_boundaries_geom","get_light_sf","get_bbox","get_census_data","get_county_light_sf","source_light_file_2000","get_light_levels","source_light_file_2010","these_states","model_prepare_data","all_states","state_boundaries","census_year_a","census_year_b","census_focus","census_year_c"],"label":["all_df","all_df_c","bbox_vec","census_df","census_df_c","census_focus_df","census_focus_df_c","county_sf","county_sf_c","light_points_df","light_points_df_c","light_sf","light_sf_c","state_boundaries_geom","get_light_sf","get_bbox","get_census_data","get_county_light_sf","source_light_file_2000","get_light_levels","source_light_file_2010","these_states","model_prepare_data","all_states","state_boundaries","census_year_a","census_year_b","census_focus","census_year_c"],"level":[8,8,3,2,2,4,4,7,7,4,4,6,6,5,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1],"color":["#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823","#354823"],"shape":["dot","dot","dot","dot","dot","dot","dot","dot","dot","dot","dot","dot","dot","dot","triangle","triangle","triangle","triangle","triangleDown","triangle","triangleDown","triangleDown","triangle","triangleDown","triangle","triangleDown","triangleDown","triangle","triangleDown"]},"edges":{"from":["get_light_sf","light_points_df","state_boundaries_geom","county_sf_c","model_prepare_data","census_focus_df","get_county_light_sf","light_sf","census_focus_df_c","get_county_light_sf","light_sf_c","county_sf","model_prepare_data","get_light_sf","light_points_df_c","state_boundaries_geom","bbox_vec","get_light_levels","source_light_file_2010","bbox_vec","get_light_levels","source_light_file_2000","census_df","get_bbox","these_states","bbox_vec","census_df_c","census_focus","these_states","bbox_vec","census_df","census_focus","these_states","all_states","census_year_c","get_census_data","census_focus_df","state_boundaries","all_states","census_year_a","get_census_data"],"to":["light_sf","light_sf","light_sf","all_df_c","all_df_c","county_sf","county_sf","county_sf","county_sf_c","county_sf_c","county_sf_c","all_df","all_df","light_sf_c","light_sf_c","light_sf_c","light_points_df_c","light_points_df_c","light_points_df_c","light_points_df","light_points_df","light_points_df","bbox_vec","bbox_vec","bbox_vec","census_focus_df_c","census_focus_df_c","census_focus_df_c","census_focus_df_c","census_focus_df","census_focus_df","census_focus_df","census_focus_df","census_df_c","census_df_c","census_df_c","state_boundaries_geom","state_boundaries_geom","census_df","census_df","census_df"],"arrows":["to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to"]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"dot","physics":false},"manipulation":{"enabled":false},"edges":{"smooth":{"type":"cubicBezier","forceDirection":"horizontal"}},"physics":{"stabilization":false},"layout":{"hierarchical":{"enabled":true,"direction":"LR"}}},"groups":null,"width":null,"height":null,"idselection":{"enabled":false,"style":"width: 150px; height: 26px","useLabels":true,"main":"Select by id"},"byselection":{"enabled":false,"style":"width: 150px; height: 26px","multiple":false,"hideColor":"rgba(200,200,200,0.5)","highlight":false},"main":{"text":"","style":"font-family:Georgia, Times New Roman, Times, serif;font-weight:bold;font-size:20px;text-align:center;"},"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","highlight":{"enabled":true,"hoverNearest":false,"degree":{"from":1,"to":1},"algorithm":"hierarchical","hideColor":"rgba(200,200,200,0.5)","labelOnly":true},"collapse":{"enabled":true,"fit":false,"resetHighlight":true,"clusterOptions":null,"keepCoord":true,"labelSuffix":"(cluster)"},"legend":{"width":0.2,"useGroups":false,"position":"right","ncol":1,"stepX":100,"stepY":100,"zoom":true,"nodes":{"label":["Up to date","Stem","Function","Object"],"color":["#354823","#899DA4","#899DA4","#899DA4"],"shape":["dot","dot","triangle","triangleDown"]},"nodesToDataframe":true}},"evals":[],"jsHooks":[]}</script>
<p><br></p>
</div>
<div id="session-information" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Session information</h3>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="end-notes.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div>
<pre><code>## R version 4.1.0 (2021-05-18)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Big Sur 10.16
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] splines   stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## 
## other attached packages:
##  [1] gt_0.3.1                 multilevelmod_0.0.0.9000 yardstick_0.0.8         
##  [4] workflowsets_0.1.0       workflows_0.2.3          tune_0.1.6              
##  [7] rsample_0.1.0            recipes_0.1.16           parsnip_0.1.7           
## [10] modeldata_0.1.1          infer_1.0.0              dials_0.0.9             
## [13] broom_0.7.9              tidymodels_0.1.3         hrbrthemes_0.8.6        
## [16] scales_1.1.1             units_0.7-2              tidycensus_1.0          
## [19] patchwork_1.1.1          ggdag_0.2.3              dagitty_0.3-1           
## [22] ggridges_0.5.3           terra_1.3-22             sf_1.0-2                
## [25] glue_1.4.2               forcats_0.5.1            stringr_1.4.0           
## [28] dplyr_1.0.7              purrr_0.3.4              readr_2.0.1             
## [31] tidyr_1.1.3              tibble_3.1.4             ggplot2_3.3.5           
## [34] tidyverse_1.3.1          targets_0.7.0           
## 
## loaded via a namespace (and not attached):
##   [1] readxl_1.3.1       uuid_0.1-4         backports_1.2.1    systemfonts_1.0.2 
##   [5] plyr_1.8.6         igraph_1.2.6       sp_1.4-5           listenv_0.8.0     
##   [9] digest_0.6.27      foreach_1.5.1      htmltools_0.5.2    fansi_0.5.0       
##  [13] checkmate_2.0.0    magrittr_2.0.1     doParallel_1.0.16  tzdb_0.1.2        
##  [17] globals_0.14.0     modelr_0.1.8       gower_0.2.2        extrafont_0.17    
##  [21] extrafontdb_1.0    hardhat_0.1.6      colorspace_2.0-2   rvest_1.0.1       
##  [25] rappdirs_0.3.3     haven_2.4.3        xfun_0.25          rgdal_1.5-23      
##  [29] callr_3.7.0        crayon_1.4.1       jsonlite_1.7.2     iterators_1.0.13  
##  [33] survival_3.2-13    tigris_1.4.1       gtable_0.3.0       ipred_0.9-11      
##  [37] V8_3.4.2           Rttf2pt1_1.3.9     DBI_1.1.1          Rcpp_1.0.7        
##  [41] GPfit_1.0-8        foreign_0.8-81     proxy_0.4-26       lava_1.6.9        
##  [45] prodlim_2019.11.13 htmlwidgets_1.5.3  httr_1.4.2         ellipsis_0.3.2    
##  [49] pkgconfig_2.0.3    nnet_7.3-16        sass_0.4.0         dbplyr_2.1.1      
##  [53] utf8_1.2.2         here_1.0.1         tidyselect_1.1.1   rlang_0.4.11      
##  [57] DiceDesign_1.9     visNetwork_2.0.9   munsell_0.5.0      cellranger_1.1.0  
##  [61] tools_4.1.0        cli_3.0.1          generics_0.1.0     evaluate_0.14     
##  [65] fastmap_1.1.0      yaml_2.2.1         processx_3.5.2     knitr_1.33        
##  [69] fs_1.5.0           tidygraph_1.2.0    future_1.22.1      xml2_1.3.2        
##  [73] compiler_4.1.0     rstudioapi_0.13    curl_4.3.2         e1071_1.7-8       
##  [77] reprex_2.0.1       lhs_1.1.1          bslib_0.2.5.1      stringi_1.7.4     
##  [81] ps_1.6.0           gdtools_0.2.3      lattice_0.20-44    Matrix_1.3-4      
##  [85] classInt_0.4-3     vctrs_0.3.8        pillar_1.6.2       lifecycle_1.0.0   
##  [89] furrr_0.2.3        jquerylib_0.1.4    data.table_1.14.0  maptools_1.1-1    
##  [93] raster_3.4-13      R6_2.5.1           bookdown_0.23      KernSmooth_2.23-20
##  [97] parallelly_1.27.0  codetools_0.2-18   boot_1.3-28        MASS_7.3-54       
## [101] assertthat_0.2.1   rprojroot_2.0.2    withr_2.4.2        parallel_4.1.0    
## [105] hms_1.1.0          grid_4.1.0         rpart_4.1-15       timeDate_3043.102 
## [109] class_7.3-19       rmarkdown_2.10     pROC_1.17.0.1      lubridate_1.7.10</code></pre>

<!-- 99-references.Rmd -->
<!-- this is a child doc of index.Rmd -->
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-CHFWXB2013" class="csl-entry">
Chander, Gyanesh, Tim Hewison, Nigel Fox, Xiangqian Wu, Xiaoxiong Xiong, and William Blackwell. 2013. <span>“Overview of Intercalibration of Satellite Instruments.”</span> <em>IEEE Transactions on Geoscience and Remote Sensing</em> 51 (March): 1056–80. <a href="https://doi.org/10.1109/TGRS.2012.2228654">https://doi.org/10.1109/TGRS.2012.2228654</a>.
</div>
<div id="ref-rs70201855" class="csl-entry">
Hsu, Feng-Chi, Kimberly E. Baugh, Tilottama Ghosh, Mikhail Zhizhin, and Christopher D. Elvidge. 2015. <span>“DMSP-OLS Radiance Calibrated Nighttime Lights Time Series with Intercalibration.”</span> <em>Remote Sensing</em> 7 (2): 1855–76. <a href="https://doi.org/10.3390/rs70201855">https://doi.org/10.3390/rs70201855</a>.
</div>
<div id="ref-WBONT2020" class="csl-entry">
WorldBank. 2020. <span>“Open Nighttime Lights Tutorial.”</span> World Bank; web page. <a href="https://worldbank.github.io/OpenNightLights/welcome.html">https://worldbank.github.io/OpenNightLights/welcome.html</a>.
</div>
</div>
<div class="footer">
<hr />
<p>By Daniel Moul (heydanielmoul via gmail)</p>
<p><img src="https://i.creativecommons.org/l/by/4.0/88x31.png" alt="CC-BY" /> This work is licensed under a <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a></p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="interpreting-the-results.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": {}
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
